// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CacheSystem() {
  return ObfuscatedCall(0, []);
}

export function ClearCache() {
  return ObfuscatedCall(1, []);
}

export function CloseApp() {
  return ObfuscatedCall(2, []);
}

export function GetCurrentPage() {
  return ObfuscatedCall(3, []);
}

export function HandleButtonClickEvent(arg1) {
  return ObfuscatedCall(4, [arg1]);
}

export function Search(arg1) {
  return ObfuscatedCall(5, [arg1]);
}

export function SetPage(arg1) {
  return ObfuscatedCall(6, [arg1]);
}

export function ToggleFavorite(arg1, arg2, arg3) {
  return ObfuscatedCall(7, [arg1, arg2, arg3]);
}
