// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeTheme(arg1) {
  return window['go']['main']['App']['ChangeTheme'](arg1);
}

export function ClearCache() {
  return window['go']['main']['App']['ClearCache']();
}

export function GetCurrentPage() {
  return window['go']['main']['App']['GetCurrentPage']();
}

export function HandleButtonClickEvent(arg1) {
  return window['go']['main']['App']['HandleButtonClickEvent'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SetPage(arg1) {
  return window['go']['main']['App']['SetPage'](arg1);
}

export function ToggleFavorite(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleFavorite'](arg1, arg2, arg3);
}
