// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {modules} from '../models';

export function HandleButtonClickEvent(arg1:any):Promise<void>;

export function Search(arg1:string):Promise<Array<modules.FileReturnStruct>>;

export function ToggleFavorite(arg1:string,arg2:string,arg3:boolean):Promise<Array<modules.FileReturnStruct>>;
